// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbpGqdo3YDfpcnoH6UXhDUbK7B7EvbmnY',
    appId: '1:147037316014:web:4f8247a912242943155e3f',
    messagingSenderId: '147037316014',
    projectId: 'holler-tag',
    authDomain: 'holler-tag.firebaseapp.com',
    storageBucket: 'holler-tag.firebasestorage.app',
    measurementId: 'G-XCF9DPGN17',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb9fJB4PB4J57V3fzjiNIOWmna3xsNtac',
    appId: '1:147037316014:android:f0360b55cfccd4ec155e3f',
    messagingSenderId: '147037316014',
    projectId: 'holler-tag',
    storageBucket: 'holler-tag.firebasestorage.app',
  );
}
